### ISSUE TITLE
On RHEL7, service state constantly changes

### ISSUE THREAD

**Issue by LightAxe** [paulbadcock/puppet-splunkuf#3]
Every puppet run results in this:

Notice: /Stage[main]/Splunkuf/Service[splunkforwarder]/enable: enable changed 'false' to 'true'

I believe the workaround is to explicitly set the service provider to rhel for RHEL7 boxen.

**Comment by LightAxe** [comment]
It was actually an issue with Oracle Enterprise Linux ("OracleLinux").  I submitted a Pull Request to fix the bug.

**Comment by paulbadcock** [comment]
Looks like a good fix, just looking into the build failure issue.

**Comment by paulbadcock** [comment]
Fixed up the build issues the spec file's parameter needed to be adjusted for the osfamily change. This was published to the puppet forge as v0.4.1

Can you confirm and let me know if the issue is now resolved?

**Comment by LightAxe** [comment]
It looks great!  Thanks for the help!  Also, I'm really excited to have found this module; it fills exactly the gap I needed to fill.
